import type { CapabilityId, ChatIntent, ResponseMode } from '@/types/chatbot';

export interface CapabilityDefinition {
  id: CapabilityId;
  intents: ChatIntent[];
  description: string;
  requiredInputs: string[];
  retrievalBlocks: string[];
  responseSections: Array<'summary' | 'actions' | 'insights' | 'recommendations' | 'escalation_guidance' | 'confidence'>;
  responseMode: ResponseMode;
  safetyConstraints: string[];
  fallbackBehavior: 'general_guidance' | 'request_context' | 'escalate';
}

const ALL_SECTIONS: CapabilityDefinition['responseSections'] = [
  'summary',
  'actions',
  'insights',
  'recommendations',
  'escalation_guidance',
  'confidence',
];

export const CAPABILITY_REGISTRY: Record<CapabilityId, CapabilityDefinition> = {
  assistant_intro: {
    id: 'assistant_intro',
    intents: ['assistant_intro'],
    description: 'BMERMS copilot intro, capabilities, and safe scope.',
    requiredInputs: [],
    retrievalBlocks: ['currentUserContext', 'openWorkPreview', 'alertsTeaser'],
    responseSections: ALL_SECTIONS,
    responseMode: 'text',
    safetyConstraints: ['safe_general_only'],
    fallbackBehavior: 'general_guidance',
  },
  my_tasks: {
    id: 'my_tasks',
    intents: ['maintenance_tip', 'work_order_help'],
    description: 'Shows active work and pending commitments for the requesting user.',
    requiredInputs: ['profileId'],
    retrievalBlocks: ['assignedWorkOrders', 'pendingApprovals', 'overduePm'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'request_context',
  },
  prioritize_tasks: {
    id: 'prioritize_tasks',
    intents: ['maintenance_tip', 'analytics_explanation'],
    description: 'Ranks urgent work by risk, urgency, and operational impact.',
    requiredInputs: ['profileId'],
    retrievalBlocks: ['decisionSupport', 'recommendationFlags', 'openWorkOrders'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'request_context',
  },
  summarize_work_order: {
    id: 'summarize_work_order',
    intents: ['work_order_help'],
    description: 'Summarizes work-order status, actions, and next steps.',
    requiredInputs: ['workOrderId'],
    retrievalBlocks: ['workOrder', 'maintenanceHistory'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'request_context',
  },
  summarize_equipment: {
    id: 'summarize_equipment',
    intents: ['equipment_lookup', 'analytics_explanation'],
    description: 'Summarizes current equipment status, reliability, and maintenance context.',
    requiredInputs: ['equipmentId'],
    retrievalBlocks: ['equipment', 'maintenanceHistory', 'riskScores', 'reliability'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'request_context',
  },
  explain_equipment_risk: {
    id: 'explain_equipment_risk',
    intents: ['analytics_explanation', 'equipment_lookup'],
    description: 'Explains risk and reliability signals for a specific asset.',
    requiredInputs: ['equipmentId'],
    retrievalBlocks: ['riskScores', 'reliability', 'replacementPriority'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'request_context',
  },
  explain_replacement_priority: {
    id: 'explain_replacement_priority',
    intents: ['analytics_explanation'],
    description: 'Explains replacement urgency, ranking, and impact tradeoffs.',
    requiredInputs: ['equipmentId?'],
    retrievalBlocks: ['replacementPriority', 'riskScores', 'reliability', 'recommendationFlags'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  explain_pm_status: {
    id: 'explain_pm_status',
    intents: ['maintenance_tip', 'analytics_explanation'],
    description: 'Explains PM compliance and overdue preventive maintenance.',
    requiredInputs: ['departmentId?'],
    retrievalBlocks: ['overduePm', 'pmCompliance'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  safe_troubleshooting: {
    id: 'safe_troubleshooting',
    intents: ['troubleshooting'],
    description: 'Provides safe first-line troubleshooting and escalation criteria.',
    requiredInputs: ['equipmentId?'],
    retrievalBlocks: ['equipment', 'manualOrSop', 'maintenanceHistory'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['no_board_level', 'no_bypass', 'first_line_only'],
    fallbackBehavior: 'escalate',
  },
  maintenance_tips: {
    id: 'maintenance_tips',
    intents: ['maintenance_tip'],
    description: 'Provides role-aware preventive maintenance tips and checks.',
    requiredInputs: ['departmentId?'],
    retrievalBlocks: ['equipment', 'pmSnapshot', 'overduePm'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  maintenance_guidance: {
    id: 'maintenance_guidance',
    intents: ['maintenance_tip', 'equipment_lookup'],
    description: 'Provides maintenance guidance using scoped asset and department context.',
    requiredInputs: ['departmentId?'],
    retrievalBlocks: ['equipment', 'workOrders', 'pmSnapshot'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  logistics_status: {
    id: 'logistics_status',
    intents: ['calibration_or_logistics'],
    description: 'Summarizes parts stock, procurement flow, and logistics blockers.',
    requiredInputs: ['departmentId?'],
    retrievalBlocks: ['lowStock', 'procurementPipeline'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  procurement_status: {
    id: 'procurement_status',
    intents: ['calibration_or_logistics'],
    description: 'Explains procurement pipeline risk and blockers impacting maintenance.',
    requiredInputs: ['departmentId?'],
    retrievalBlocks: ['procurementPipeline', 'lowStock', 'openWorkOrders'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  pending_approvals: {
    id: 'pending_approvals',
    intents: ['work_order_help', 'maintenance_tip'],
    description: 'Lists pending approvals and likely operational impact.',
    requiredInputs: ['profileId'],
    retrievalBlocks: ['maintenanceRequests', 'disposalRequests', 'procurementPipeline'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'request_context',
  },
  approval_tasks: {
    id: 'approval_tasks',
    intents: ['work_order_help', 'maintenance_tip'],
    description: 'Lists pending approvals in maintenance, disposal, and procurement workflows.',
    requiredInputs: ['profileId'],
    retrievalBlocks: ['maintenanceRequests', 'disposalRequests', 'procurementPipeline'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'request_context',
  },
  alerts_and_escalations: {
    id: 'alerts_and_escalations',
    intents: ['analytics_explanation', 'troubleshooting'],
    description: 'Reports active alert state and escalations requiring action.',
    requiredInputs: ['departmentId?'],
    retrievalBlocks: ['recommendationFlags', 'recentAlerts'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  decision_support_analysis: {
    id: 'decision_support_analysis',
    intents: ['analytics_explanation'],
    description: 'Explains triage, readiness, and workload analytics snapshots.',
    requiredInputs: ['departmentId?'],
    retrievalBlocks: ['decisionSupport'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  summarize_department_readiness: {
    id: 'summarize_department_readiness',
    intents: ['analytics_explanation'],
    description: 'Summarizes department clinical readiness and essential equipment posture from snapshots.',
    requiredInputs: ['departmentId?'],
    retrievalBlocks: ['readinessSnapshot', 'workloadSnapshot', 'recommendationFlags'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  training_status: {
    id: 'training_status',
    intents: ['maintenance_tip'],
    description: 'Summarizes training requests, scheduling posture, and workload context.',
    requiredInputs: ['departmentId?'],
    retrievalBlocks: ['trainingRequests', 'workloadSnapshot'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  disposal_status: {
    id: 'disposal_status',
    intents: ['maintenance_tip'],
    description: 'Summarizes disposal pipeline status and pending approvals.',
    requiredInputs: ['departmentId?'],
    retrievalBlocks: ['disposalPipeline', 'disposalApprovals'],
    responseSections: ALL_SECTIONS,
    responseMode: 'json',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  general_fallback: {
    id: 'general_fallback',
    intents: ['maintenance_tip'],
    description: 'Safe, context-aware fallback for unclear or unknown requests.',
    requiredInputs: [],
    retrievalBlocks: ['lightweightContext'],
    responseSections: ALL_SECTIONS,
    responseMode: 'text',
    safetyConstraints: ['safe_general_only'],
    fallbackBehavior: 'general_guidance',
  },
  general_system_fallback: {
    id: 'general_system_fallback',
    intents: ['maintenance_tip'],
    description: 'Safe, contextual fallback preserving system-operational tone.',
    requiredInputs: [],
    retrievalBlocks: ['lightweightContext'],
    responseSections: ALL_SECTIONS,
    responseMode: 'text',
    safetyConstraints: ['safe_general_only'],
    fallbackBehavior: 'general_guidance',
  },
};

export function getCapabilityDefinition(capability: CapabilityId): CapabilityDefinition {
  return CAPABILITY_REGISTRY[capability] ?? CAPABILITY_REGISTRY.general_system_fallback;
}

const CAPABILITY_ALIASES: Record<string, CapabilityId> = {
  pending_approvals: 'pending_approvals',
  approval_tasks: 'pending_approvals',
  maintenance_tips: 'maintenance_tips',
  procurement_status: 'procurement_status',
  general_system_fallback: 'general_system_fallback',
  general_fallback: 'general_system_fallback',
};

export function normalizeCapabilityId(capability: CapabilityId | string): CapabilityId {
  return CAPABILITY_ALIASES[capability] ?? (capability as CapabilityId);
}
