import type { CapabilityId, ChatIntent, ResponseMode } from '@/types/chatbot';

export interface CapabilityDefinition {
  id: CapabilityId;
  intents: ChatIntent[];
  description: string;
  requiredInputs: string[];
  retrievalBlocks: string[];
  responseSections: Array<'summary' | 'actions' | 'insights' | 'recommendations' | 'escalation_guidance' | 'confidence'>;
  responseMode: ResponseMode;
  safetyConstraints: string[];
  fallbackBehavior: 'general_guidance' | 'request_context' | 'escalate';
}

const ALL_SECTIONS: CapabilityDefinition['responseSections'] = [
  'summary',
  'actions',
  'insights',
  'recommendations',
  'escalation_guidance',
  'confidence',
];

export const CAPABILITY_REGISTRY: Record<CapabilityId, CapabilityDefinition> = {
  assistant_intro: {
    id: 'assistant_intro',
    intents: ['assistant_intro', 'general_help'],
    description: 'BMEDIS copilot intro, capabilities, and safe scope.',
    requiredInputs: [],
    retrievalBlocks: ['currentUserContext', 'openWorkPreview', 'notificationsTeaser'],
    responseSections: ALL_SECTIONS,
    responseMode: 'local',
    safetyConstraints: ['safe_general_only'],
    fallbackBehavior: 'general_guidance',
  },
  general_conversation: {
    id: 'general_conversation',
    intents: ['general_conversation', 'off_topic_safe'],
    description: 'Short harmless conversational responses with BMEDIS redirect.',
    requiredInputs: [],
    retrievalBlocks: [],
    responseSections: ALL_SECTIONS,
    responseMode: 'text',
    safetyConstraints: ['safe_general_only'],
    fallbackBehavior: 'general_guidance',
  },
  off_topic_safe: {
    id: 'off_topic_safe',
    intents: ['off_topic_safe'],
    description: 'Handles harmless non-BMEDIS prompts without forcing system data retrieval.',
    requiredInputs: [],
    retrievalBlocks: [],
    responseSections: ALL_SECTIONS,
    responseMode: 'text',
    safetyConstraints: ['safe_general_only'],
    fallbackBehavior: 'general_guidance',
  },
  my_tasks: {
    id: 'my_tasks',
    intents: ['maintenance_tip', 'work_order_help', 'work_order_status', 'maintenance_status'],
    description: 'Shows active work and pending commitments for the requesting user.',
    requiredInputs: ['profileId'],
    retrievalBlocks: ['assignedWorkOrders', 'pendingApprovals', 'overduePm'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'request_context',
  },
  prioritize_tasks: {
    id: 'prioritize_tasks',
    intents: ['maintenance_tip', 'analytics_explanation', 'work_order_status', 'maintenance_status', 'decision_support', 'dashboard_summary'],
    description: 'Ranks urgent work by risk, urgency, and operational impact.',
    requiredInputs: ['profileId'],
    retrievalBlocks: ['decisionSupport', 'recommendationFlags', 'openWorkOrders'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'request_context',
  },
  summarize_work_order: {
    id: 'summarize_work_order',
    intents: ['work_order_help', 'work_order_status', 'maintenance_status'],
    description: 'Summarizes work-order status, actions, and next steps.',
    requiredInputs: ['workOrderId'],
    retrievalBlocks: ['workOrder', 'maintenanceHistory'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'request_context',
  },
  summarize_equipment: {
    id: 'summarize_equipment',
    intents: ['asset_summary', 'inventory_search', 'equipment_lookup', 'equipment_history', 'analytics_explanation'],
    description: 'Summarizes current equipment status, reliability, and maintenance context.',
    requiredInputs: ['equipmentId'],
    retrievalBlocks: ['equipment', 'maintenanceHistory', 'riskScores', 'reliability'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'request_context',
  },
  explain_equipment_risk: {
    id: 'explain_equipment_risk',
    intents: ['analytics_explanation', 'equipment_lookup', 'risk_analysis', 'reliability_metrics', 'replacement_priority'],
    description: 'Explains risk and reliability signals for a specific asset.',
    requiredInputs: ['equipmentId'],
    retrievalBlocks: ['riskScores', 'reliability', 'replacementPriority'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'request_context',
  },
  explain_pm_status: {
    id: 'explain_pm_status',
    intents: ['maintenance_tip', 'analytics_explanation', 'preventive_maintenance', 'calibration_status'],
    description: 'Explains PM compliance and overdue preventive maintenance.',
    requiredInputs: ['departmentId?'],
    retrievalBlocks: ['overduePm', 'pmCompliance'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  safe_troubleshooting: {
    id: 'safe_troubleshooting',
    intents: ['troubleshooting', 'safe_troubleshooting'],
    description: 'Provides safe first-line troubleshooting and escalation criteria.',
    requiredInputs: ['equipmentId?'],
    retrievalBlocks: ['equipment', 'manualOrSop', 'maintenanceHistory'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['no_board_level', 'no_bypass', 'first_line_only'],
    fallbackBehavior: 'escalate',
  },
  maintenance_tips: {
    id: 'maintenance_tips',
    intents: ['maintenance_tip'],
    description: 'Provides role-aware preventive maintenance tips and checks.',
    requiredInputs: ['departmentId?'],
    retrievalBlocks: ['equipment', 'pmSnapshot', 'overduePm'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  logistics_status: {
    id: 'logistics_status',
    intents: ['calibration_or_logistics', 'spare_parts_lookup', 'logistics_stock'],
    description: 'Summarizes parts stock, procurement flow, and logistics blockers.',
    requiredInputs: ['departmentId?'],
    retrievalBlocks: ['lowStock', 'procurementPipeline'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  procurement_status: {
    id: 'procurement_status',
    intents: ['calibration_or_logistics', 'procurement_status'],
    description: 'Explains procurement pipeline risk and blockers impacting maintenance.',
    requiredInputs: ['departmentId?'],
    retrievalBlocks: ['procurementPipeline', 'lowStock', 'openWorkOrders'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  summarize_alerts: {
    id: 'summarize_alerts',
    intents: ['analytics_explanation', 'troubleshooting'],
    description: 'Summarizes active Notification Center signals and escalations requiring action.',
    requiredInputs: ['departmentId?'],
    retrievalBlocks: ['recommendationFlags', 'recentNotifications'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  summarize_department_readiness: {
    id: 'summarize_department_readiness',
    intents: ['analytics_explanation', 'dashboard_summary', 'decision_support'],
    description: 'Summarizes department clinical readiness and essential equipment posture from snapshots.',
    requiredInputs: ['departmentId?'],
    retrievalBlocks: ['readinessSnapshot', 'workloadSnapshot', 'recommendationFlags'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  training_status: {
    id: 'training_status',
    intents: ['maintenance_tip', 'training_status'],
    description: 'Summarizes training requests, scheduling posture, and workload context.',
    requiredInputs: ['departmentId?'],
    retrievalBlocks: ['trainingRequests', 'workloadSnapshot'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  disposal_status: {
    id: 'disposal_status',
    intents: ['maintenance_tip', 'disposal_status'],
    description: 'Summarizes disposal pipeline status and pending approvals.',
    requiredInputs: ['departmentId?'],
    retrievalBlocks: ['disposalPipeline', 'disposalApprovals'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'general_guidance',
  },
  qr_asset_context: {
    id: 'qr_asset_context',
    intents: ['equipment_lookup', 'analytics_explanation'],
    description: 'Explains QR asset identity, coverage, scan evidence, and label status when supported by retrieved records.',
    requiredInputs: ['equipmentId?'],
    retrievalBlocks: ['equipment', 'qrCoverage', 'scanEvidence'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['role_scope_only', 'no_raw_token_leak'],
    fallbackBehavior: 'request_context',
  },
  offline_sync_status: {
    id: 'offline_sync_status',
    intents: ['analytics_explanation'],
    description: 'Summarizes offline queue/sync status and conflicts. Phase 1 marks detailed page-aware tools as planned.',
    requiredInputs: [],
    retrievalBlocks: ['offlineSyncSummary'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'request_context',
  },
  report_summary: {
    id: 'report_summary',
    intents: ['analytics_explanation', 'report_help'],
    description: 'Explains report evidence and methodology from available context without inventing report data.',
    requiredInputs: ['route?'],
    retrievalBlocks: ['reportContext'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['role_scope_only'],
    fallbackBehavior: 'request_context',
  },
  metric_debug: {
    id: 'metric_debug',
    intents: ['analytics_explanation'],
    description: 'Developer-oriented explanation for metric source, zero/null values, and source tables.',
    requiredInputs: ['route?', 'metric?'],
    retrievalBlocks: ['toolTrace', 'evidenceSignals'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['developer_only_for_raw_trace'],
    fallbackBehavior: 'request_context',
  },
  copilot_diagnostics: {
    id: 'copilot_diagnostics',
    intents: ['analytics_explanation'],
    description: 'Developer-only copilot routing, provider, parser, telemetry, and smoke-test diagnostics.',
    requiredInputs: [],
    retrievalBlocks: ['chatTelemetry', 'usageSummary'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['developer_only_for_raw_trace'],
    fallbackBehavior: 'request_context',
  },
  usage_status: {
    id: 'usage_status',
    intents: ['analytics_explanation'],
    description: 'Explains app-tracked Gemini usage, limits, and whether counts are provider-reported or estimated.',
    requiredInputs: [],
    retrievalBlocks: ['copilotUsageEvents'],
    responseSections: ALL_SECTIONS,
    responseMode: 'structured',
    safetyConstraints: ['no_api_keys', 'no_google_billing_claims'],
    fallbackBehavior: 'request_context',
  },
  unsafe_or_restricted: {
    id: 'unsafe_or_restricted',
    intents: ['unsafe', 'unsafe_request', 'too_detailed', 'out_of_scope'],
    description: 'Handles restricted unsafe requests with policy-safe responses.',
    requiredInputs: [],
    retrievalBlocks: [],
    responseSections: ALL_SECTIONS,
    responseMode: 'local',
    safetyConstraints: ['restricted'],
    fallbackBehavior: 'escalate',
  },
  general_system_fallback: {
    id: 'general_system_fallback',
    intents: ['general_conversation', 'maintenance_tip', 'workflow_help', 'insufficient_context'],
    description: 'Safe, contextual fallback preserving system-operational tone.',
    requiredInputs: [],
    retrievalBlocks: ['lightweightContext'],
    responseSections: ALL_SECTIONS,
    responseMode: 'text',
    safetyConstraints: ['safe_general_only'],
    fallbackBehavior: 'general_guidance',
  },
};

export function getCapabilityDefinition(capability: CapabilityId): CapabilityDefinition {
  return CAPABILITY_REGISTRY[capability] ?? CAPABILITY_REGISTRY.general_system_fallback;
}

const CAPABILITY_ALIASES: Record<string, CapabilityId> = {
  pending_approvals: 'my_tasks',
  approval_tasks: 'my_tasks',
  maintenance_tips: 'maintenance_tips',
  procurement_status: 'procurement_status',
  alerts_and_escalations: 'summarize_alerts',
  decision_support_analysis: 'summarize_department_readiness',
  maintenance_guidance: 'maintenance_tips',
  explain_replacement_priority: 'explain_equipment_risk',
  qr_context: 'qr_asset_context',
  qr_coverage: 'qr_asset_context',
  scan_evidence: 'qr_asset_context',
  offline_status: 'offline_sync_status',
  sync_status: 'offline_sync_status',
  report_explanation: 'report_summary',
  metric_source: 'metric_debug',
  ai_diagnostics: 'copilot_diagnostics',
  copilot_health: 'copilot_diagnostics',
  gemini_usage: 'usage_status',
  general_fallback: 'general_system_fallback',
  general_system_fallback: 'general_system_fallback',
};

export function normalizeCapabilityId(capability: CapabilityId | string): CapabilityId {
  return CAPABILITY_ALIASES[capability] ?? (capability as CapabilityId);
}
